### PR TITLE
add electromagnetic-field example

### PR DESCRIPTION
**Pull request by dhaberl**
Hello, 

I added the electromagnetic-field example to the existing EMFields folder and moved the content of this folder (an example for electric and/or magnetic fields) into a separate folder inside the EMFields folder called electric-and-magnetic-field.

This is the example to the pull request: [Add custom electromagnetic field maps #423](https://github.com/OpenGATE/Gate/pull/423)

Best,
David

### CODE REVIEW

**Comment by dsarrut** [comment]
Really great, thanks a lot! 
Before we merge, I have a question about the files in the output folder (*.root in particular). Are they needed? 
- If no, I think it is better to remove them before merging to reduce the overall size. In that case, I am sorry, I think you should redo another PR (without the files) because updating this PR is not enough as the files will remain in the history
- If yes, please, for what purpose? 
thanks

**Comment by SimonRit** [comment]
>     In that case, I am sorry, I think you should redo another PR (without the files) because updating this PR is not enough as the files will remain in the history

You can amend this PR, no need to do a new one. For example
```
git rm dosimetry/EMFields/electric-and-magnetic-field/output/dose-PDD-Dose-Squared.root
git commit --amend
```
But in that case, I think the files are already [in the master branch](https://github.com/OpenGATE/GateContrib/tree/master/dosimetry/EMFields/output), this PR only moves them.

**Comment by dhaberl** [comment]
Hello David,
Hello Simon, 

Yes, that's correct @SimonRit . The *.root files in the output folder were already in the master branch as part of an already existing example for electric and magnetic fields. I just moved the existing example into a dedicated folder called "electric-and-magnetic-field" and added my example "electromagnetic-field".

I think they used the root files to extract the beam deflection curves, so removing them would break their example.

**Comment by dsarrut** [comment]
great, thanks a lot!

**Pull request merged**
